when I click fetch adventurswork data button I get this error on the UI: can you identify the issue and how to fix it?
Error Fetching Data
Failed to connect to AAS: Failed to connect to eastus.asazure.windows.net/resturantsas:1433 in 30000ms

in console I see the following :
6src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:01 GMT] : [] : @azure/msal-react@2.2.0 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
hot-reloader-client.tsx:371 [Fast Refresh] rebuilding
hot-reloader-client.tsx:116 [Fast Refresh] done in 23ms
src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:01 GMT] : [] : @azure/msal-browser@3.28.1 : Info - BrowserCacheManager: addTokenKey - idToken added to map
src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:01 GMT] : [] : @azure/msal-browser@3.28.1 : Info - BrowserCacheManager: addTokenKey - accessToken added to map
src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:01 GMT] : [] : @azure/msal-browser@3.28.1 : Info - BrowserCacheManager: addTokenKey - refreshToken added to map
3src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:01 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:01 GMT] : [] : @azure/msal-react@2.2.0 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:01 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:01 GMT] : [] : @azure/msal-react@2.2.0 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
7src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:01 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
2src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:10 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:10 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getAccessToken - No token found
src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:10 GMT] : [0196a864-a63b-730b-8b42-4a79b742aa86] : @azure/msal-common@14.16.0 : Info - Token refresh is required due to cache outcome: 2
4src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:10 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:10 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getRefreshToken - returning refresh token
src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:10 GMT] : [] : @azure/msal-browser@3.28.1 : Info - BrowserCacheManager: addTokenKey - accessToken added to map
2src_fb167dc7._.js:50 [Wed, 07 May 2025 01:38:10 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
hot-reloader-client.tsx:371 [Fast Refresh] rebuilding
hot-reloader-client.tsx:116 [Fast Refresh] done in 463ms
hot-reloader-client.tsx:371 [Fast Refresh] rebuilding
hot-reloader-client.tsx:116 [Fast Refresh] done in 51ms
get-aas-data:1

           Failed to load resource: the server responded with a status of 500 (Internal Server Error)Understand this error
hot-reloader-client.tsx:371 [Fast Refresh] rebuilding
FetchDataButton.tsx:61 Error fetching AAS data: Error: Failed to connect to AAS: Failed to connect to eastus.asazure.windows.net/resturantsas:1433 in 30000ms
    at handleFetchData (FetchDataButton.tsx:51:15)
error @ intercept-console-error.ts:41
handleFetchData @ FetchDataButton.tsx:61Understand this error
hot-reloader-client.tsx:116 [Fast Refresh] done in 60ms
hot-reloader-client.tsx:371 [Fast Refresh] rebuilding
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-react@2.2.0 : Info - useAccount - Updating account
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [0196a865-50f6-7dc5-bc59-d0778f691f5f] : msal.js.browser@3.28.1 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-react@2.2.0 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from none to handleRedirect
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-react@2.2.0 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from none to handleRedirect
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-react@2.2.0 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-react@2.2.0 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-common@14.16.0 : Info - CacheManager:getIdToken - Returning ID token
msalConfig.ts:30 [Wed, 07 May 2025 01:38:54 GMT] : [] : @azure/msal-react@2.2.0 : Info - useAccount - Updating account
hot-reloader-client.tsx:116 [Fast Refresh] done in 14ms